<%@ page contentType="text/html; charset=Windows-31J" %>
                          <input type="hidden" name="Condition"           id="Condition"           value="<%=condition%>">
                          <input type="hidden" name="BirthdayCheck"       id="BirthdayCheck"       value="<%=birthday_check%>">
                          <input type="hidden" name="BirthdayStartMonth"  id="BirthdayStartMonth"  value="<%=param_birthday_startmonth%>">
                          <input type="hidden" name="BirthdayStartDay"    id="BirthdayStartDay"    value="<%=param_birthday_startday%>">
                          <input type="hidden" name="BirthdayEndMonth"    id="BirthdayEndMonth"    value="<%=param_birthday_endmonth%>">
                          <input type="hidden" name="BirthdayEndDay"      id="BirthdayEndDay"      value="<%=param_birthday_endday%>">
                          <input type="hidden" name="MemorialCheck"       id="MemorialCheck"       value="<%=memorial_check%>">
                          <input type="hidden" name="MemorialStartMonth"  id="MemorialStartMonth"  value="<%=param_memorial_startmonth%>">
                          <input type="hidden" name="MemorialStartDay"    id="MemorialStartDay"    value="<%=param_memorial_startday%>">
                          <input type="hidden" name="MemorialEndMonth"    id="MemorialEndMonth"    value="<%=param_memorial_endmonth%>">
                          <input type="hidden" name="MemorialEndDay"      id="MemorialEndDay"      value="<%=param_memorial_endday%>">
                          <input type="hidden" name="LastDayCheck"        id="LastDayCheck"        value="<%=lastday_check%>">
                          <input type="hidden" name="LastDayStartYear"    id="LastDayStartYear"    value="<%=param_lastday_startyear%>">
                          <input type="hidden" name="LastDayStartMonth"   id="LastDayStartMonth"   value="<%=param_lastday_startmonth%>">
                          <input type="hidden" name="LastDayStartDay"     id="LastDayStartDay"     value="<%=param_lastday_startday%>">
                          <input type="hidden" name="LastDayEndYear"      id="LastDayEndYear"      value="<%=param_lastday_endyear%>">
                          <input type="hidden" name="LastDayEndMonth"     id="LastDayEndMonth"     value="<%=param_lastday_endmonth%>">
                          <input type="hidden" name="LastDayEndDay"       id="LastDayEndDay"       value="<%=param_lastday_endday%>">
                          <input type="hidden" name="CountCheck"          id="CountCheck"          value="<%=count_check%>">
                          <input type="hidden" name="CountStart"          id="CountStart"          value="<%=param_count_start%>">
                          <input type="hidden" name="CountEnd"            id="CountEnd"            value="<%=param_count_end%>">
                          <input type="hidden" name="TotalCheck"          id="TotalCheck"          value="<%=total_check%>">
                          <input type="hidden" name="TotalStart"          id="TotalStart"          value="<%=param_total_start%>">
                          <input type="hidden" name="TotalEnd"            id="TotalEnd"            value="<%=param_total_end%>">
                          <input type="hidden" name="PointCheck"          id="PointCheck"          value="<%=point_check%>">
                          <input type="hidden" name="PointStart"          id="PointStart"          value="<%=param_point_start%>">
                          <input type="hidden" name="PointEnd"            id="PointEnd"            value="<%=param_point_end%>">
                          <input type="hidden" name="Point2Check"         id="Point2Check"         value="<%=point2_check%>">
                          <input type="hidden" name="Point2Start"         id="Point2Start"         value="<%=param_point2_start%>">
                          <input type="hidden" name="Point2End"           id="Point2End"           value="<%=param_point2_end%>">
                          <input type="hidden" name="CustomidCheck"       id="CustomidCheck"       value="<%=customid_check%>">
                          <input type="hidden" name="CustomidStart"       id="CustomidStart"       value="<%=param_customid_start%>">
                          <input type="hidden" name="CustomidEnd"         id="CustomidEnd"         value="<%=param_customid_end%>">
                          <input type="hidden" name="MailaddressCheck"    id="MailaddressCheck"    value="<%=mailaddress_check%>">
                          <input type="hidden" name="Mailaddress"         id="Mailaddress"         value="<%=param_mailaddress%>">
                          <input type="hidden" name="LastSendCheck"       id="LastSendCheck"       value="<%=lastsend_check%>">
                          <input type="hidden" name="LastSendStartYear"   id="LastSendStartYear"   value="<%=param_lastsend_startyear%>">
                          <input type="hidden" name="LastSendStartMonth"  id="LastSendStartMonth"  value="<%=param_lastsend_startmonth%>">
                          <input type="hidden" name="LastSendStartDay"    id="LastSendStartDay"    value="<%=param_lastsend_startday%>">
                          <input type="hidden" name="LastSendStartHour"   id="LastSendStartHour"   value="<%=param_lastsend_starthour%>">
                          <input type="hidden" name="LastSendStartMinute" id="LastSendStartMinute" value="<%=param_lastsend_startminute%>">
                          <input type="hidden" name="LastSendEndYear"     id="LastSendEndYear"     value="<%=param_lastsend_endyear%>">
                          <input type="hidden" name="LastSendEndMonth"    id="LastSendEndMonth"    value="<%=param_lastsend_endmonth%>">
                          <input type="hidden" name="LastSendEndDay"      id="LastSendEndDay"      value="<%=param_lastsend_endday%>">
                          <input type="hidden" name="LastSendEndHour"     id="LastSendEndHour"     value="<%=param_lastsend_endhour%>">
                          <input type="hidden" name="LastSendEndMinute"   id="LastSendEndMinute"   value="<%=param_lastsend_endminute%>">
                          <input type="hidden" name="Query"               id="Query"               value="<%=ReplaceString.HTMLEscape(param_query.replace("SELECT address,custom_id FROM mag_address WHERE hotel_id IN (","").replace("AND state=1 AND unknown_flag=0","").replace("address LIKE","%AL%"))%>">
